import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { tokensToCssVariables } from '../src/tokens/index.ts'

const scriptDir = dirname(fileURLToPath(import.meta.url))
const outDir = join(scriptDir, '../src/css')
const outPath = join(outDir, 'tokens.css')

const vars = tokensToCssVariables()
const lines = Object.entries(vars)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([name, value]) => `  ${name}: ${value};`)

const css = `/* Generated by scripts/generate-tokens-css.ts — do not edit by hand. */
/* Source of truth: src/tokens/*.ts */

:root {
${lines.join('\n')}
}
`

mkdirSync(outDir, { recursive: true })
writeFileSync(outPath, css, 'utf8')
console.log(`Wrote ${outPath} (${lines.length} custom properties)`)
