/**
 * Generates the public UI CSS bundle at `src/css/ui.css`.
 * Includes brand tokens, theme bridge, and compiled component styles.
 * Do not hand-edit the output file.
 */
import { spawnSync } from 'node:child_process'
import { existsSync, mkdirSync, readFileSync, unlinkSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const scriptDir = dirname(fileURLToPath(import.meta.url))
const root = join(scriptDir, '..')
const cssDir = join(root, 'src/css')
const tokensPath = join(cssDir, 'tokens.css')
const entryPath = join(root, 'src/ui/styles/entry.css')
const outPath = join(cssDir, 'ui.css')
const tmpPath = join(cssDir, '.ui-compiled.tmp.css')
const cliBin = join(
  root,
  'node_modules',
  '@tailwindcss',
  'cli',
  process.platform === 'win32' ? 'dist/index.mjs' : 'dist/index.mjs',
)

mkdirSync(cssDir, { recursive: true })

if (!existsSync(tokensPath)) {
  console.error('Missing tokens.css — run `npm run tokens:generate` first.')
  process.exit(1)
}

const result = spawnSync(
  process.execPath,
  [cliBin, '-i', entryPath, '-o', tmpPath],
  {
    cwd: root,
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'pipe'],
  },
)

if (result.status !== 0) {
  console.error(result.stderr || result.stdout || 'Tailwind CSS compilation failed')
  process.exit(result.status ?? 1)
}

const compiled = readFileSync(tmpPath, 'utf8')
const banner = `/* Generated by scripts/generate-ui-css.ts — do not edit by hand. */
/* Includes: brand tokens, theme bridge, and UI primitive styles. */
`

writeFileSync(outPath, `${banner}\n${compiled}`, 'utf8')

try {
  unlinkSync(tmpPath)
} catch {
  // ignore cleanup failure
}

console.log(`Wrote ${outPath} (${compiled.length} bytes compiled CSS)`)
