import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import { tokensToCssVariables } from './index'

const root = join(dirname(fileURLToPath(import.meta.url)), '../..')

/** Dashboard surface kit custom properties that must exist after tokens:generate. */
const DASHBOARD_TOKEN_VARS = [
  '--semantic-positive',
  '--semantic-negative',
  '--color-positive',
  '--color-negative',
  '--density-header-padding-y',
  '--density-header-padding-x',
  '--density-header-gap',
  '--density-header-min-height',
  '--density-header-control-gap',
  '--chart-frame',
  '--chart-frame-border',
  '--chart-plot',
  '--chart-axis',
  '--chart-grid',
  '--chart-sparkline-stroke',
  '--chart-sparkline-fill',
  '--chart-chrome',
] as const

describe('dashboard surface tokens', () => {
  it('exposes semantic up/down, header density, and chart-chrome vars from TS source', () => {
    const generated = tokensToCssVariables()
    for (const variable of DASHBOARD_TOKEN_VARS) {
      expect(generated[variable], variable).toBeTruthy()
    }
  })

  it('keeps generated tokens.css aligned with the TS source of truth', () => {
    const css = readFileSync(join(root, 'src/css/tokens.css'), 'utf8')
    expect(css).toContain('Generated by scripts/generate-tokens-css.ts')
    expect(css).toContain('do not edit by hand')

    for (const variable of DASHBOARD_TOKEN_VARS) {
      expect(css).toContain(variable)
    }
  })
})
